### ISSUE TITLE
No able to install

### ISSUE THREAD

**Issue by Sachinart** [LeakIX/LeakIXClient#3]
Hi, It's throwing this error while installing:

go: gitlab.nobody.run/tbi/core@v0.0.0-20201124161030-42e21c6deb8e: unrecognized import path "gitlab.nobody.run/tbi/core": reading https://gitlab.nobody.run/tbi/core?go-get=1: 404 Not Found
        server response: 404 page not found

Could you please fix that?

Thank You!

**Comment by gboddin** [comment]
Hi, we have fixed  the issue in 1.0.1 !

Regards,
